services:
  market-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    networks:
      - market-internal
    env_file: .env

networks:
  market-internal:
    external: true
